services:
  # Combined API and Dashboard
  - type: web
    name: 4th-down-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn apppreview:app.server --bind 0.0.0.0:$PORT --workers 2 --threads 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PORT
        generateValue: true
